# Bio
&nbsp;

<div align="justify">
I'm currently a postdoctoral researcher at the University of York, working on the <a href="https://multiage.github.io" target="_blank">MultiAge</a> project of <a href="https://www.york.ac.uk/psychology/staff/academicstaff/amdb504/" target="_blank">Angela de Bruin</a>. MultiAge studies bilingual language control in healthy aging and aging with mild cognitive impairment. In the past, I worked at the University of Nottingham on frontotemporal dementia using multimodal (structural, task fMRI, resting-state fMRI and MR spectroscopic) neuroimaging data. 

My research interests revolve around bi- and multilingualism, language control, and cognition in dementia and in the healthy adult brain. I'm particularly interested in how individual bilingual experiences could affect brain functioning and structure in (late) adulthood (i.e., does bilingualism provide a cognitive/brain reserve). I do my best to carry out my work according to the field's Open Scholarship standards for transparency and reproducibility, and I also investigate the application of Open Scholarship myself, as a proud member of the <a href="https://forrt.org/" target="_blank">Framework for Open and Reproducible Research Training (FORRT)</a> and the <a href="https://feministwonderlabcoll.github.io/feministwonderlab/" target="_blank">Feminist Wonder Lab</a>. 

I graduated from my PhD in 2024, and my work investigated the individual differences in the bilingual language switching and cognition abilities. I graduated with an MSc in Evolution of Language and Cognition (University of Edinburgh, 2017) and an MSc in Intercultural Communication (University of Warwick, 2015). My MSc dissertations studied the learnability of evidentiality grammatical structures for bilinguals, and the cultural identity of bilingual speakers of endangered Mesoamerican languages. I earned my undergraduate degree in Psychology in 2010 from Sofia University "St. Kliment Ohridski", Bulgaria. 


</div>
&nbsp;

## Research and teaching experience
&nbsp;

<div align="justify">
* **November 2024 - currently: Postdoctoral Research Associate at the Department of Psychology, University of York**. I'm working on <a href="https://multiage.github.io" target="_blank">MultiAge</a>, a longitudinal multi-study project on bilingualism, healthy aging and aging with mild cognitive impairment. My participants are younger and older adults with a minority-language bilingual background, living in the UK. I'm collecting behavioural and fNIRS data.
* **June 2024 - October 2024: Postdoctoral Researcher at Birkbeck College, University of London**. I collected behavioural, eye-tracking, video, and fNIRS data from 3–7-year-old children dyads, to investigate brain synchrony in social interaction. I also developed lab procedures for an immersive virtual-reality, eye-tracking and fNIRS study on primary-school children with ADHD.
* **March 2024 - currently: Teaching Fellow at the School of Psychology, University of Birmingham**. I'm developing module content and teaching on an innovative fully digital MSc programme in Mental Health. I'm the module creator and lead for Translational Cognitive Neuroscience. 
*	**May 2023 – May 2024: Postdoctoral Fellow at the School of Psychology, University of Nottingham**. I collected and analysed multimodal (f)MRI/MRS, behavioural and neuropsychological data of frontotemporal and Alzheimer's dementia patients and healthy older adults, to answer questions about the neural changes in dementia and their relationship to cognition. I also gained some practical experience in focused ultrasound brain stimulation.
*	**January 2022 – July 2023: Lecturer in Psychology at the Department of Education and Social Justice, University of Birmingham**. I was the module lead for Quantitative Research Methods I, for Psychology of Education undergraduates. I also acted as a primary supervisor of MSc dissertations and mentored students. 
*	**June – September 2021: Research Assistant at the School of Psychology, University of Birmingham**. I collected data on the project <a href="https://readyornotstudy.uk/" target="_blank">Ready or Not</a>, on the social, emotional and cognitive development of reception-aged children, and their challenges in transitioning to the first school year. 
* **April 2021 – April 2022: Research Assistant at the School of Psychology, University of Birmingham**. I collected EEG data for the ESRC project <a href="https://research.birmingham.ac.uk/en/projects/the-effects-of-individual-differences-in-bilingual-experience-on-" target="_blank">The effects of individual differences in bilingual experience on cognitive control networks</a>. 
*	**September 2018 – April 2022: Teaching Associate at the School of Psychology, University of Birmingham**. Teaching, student assessment and supporting the lead teaching staff on various postgraduate and undergraduate courses.
*	**August 2019 – January 2020: Research Assistant at the School of Psychology, University of Birmingham**. I collected data from bilinguals and monolinguals for a research project on audio-visual information integration during language perception.
*	**June – November 2018: Language Consultant at <a href="https://what3words.com/about" target="_blank">What3Words</a>**. I consulted and advised the team on Bulgarian language features and assisted the development of the What3Words location application for Bulgaria. 
*	**November 2017 – January 2021: Sleep Study Research Assistant, at the Nuffield Department of Clinical Neurosciences, the University of Oxford**. I collected sleep polysomnography and tDCS data.
*	**May – August 2017: Research Assistant, at the University of Edinburgh**. I recruited and tested children on a fNIRS paradigm for a project examining reactive and proactive control markers. 
*	**February - June 2014: Psychology Intern in Cognitive Psychophysiology, Institute of Neurobiology, Bulgarian Academy of Sciences**, Sofia, Bulgaria. 
*	**December 2012 – February 2013: Psychology Intern in the Centre for Military Psychology and Psychological Assessment, and the Psychiatry Clinic of Military Medical Academy**, Sofia, Bulgaria. 
</div>
&nbsp;



